[2024-05-09T10:47:07.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T10:47:07.970+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T10:46:33.057547+00:00 [queued]>
[2024-05-09T10:47:07.976+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T10:46:33.057547+00:00 [queued]>
[2024-05-09T10:47:07.978+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-09T10:47:08.020+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-09 10:46:33.057547+00:00
[2024-05-09T10:47:08.029+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-09T10:46:33.057547+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp7_gbsk7x']
[2024-05-09T10:47:08.030+0000] {standard_task_runner.py:63} INFO - Started process 91674 to run task
[2024-05-09T10:47:08.035+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask transform_load_weather_data
[2024-05-09T10:47:08.114+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T10:46:33.057547+00:00 [running]> on host ubuntu2204
[2024-05-09T10:47:08.309+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T10:46:33.057547+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T10:46:33.057547+00:00'
[2024-05-09T10:47:08.312+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T10:47:08.322+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T10:47:08.323+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow/dags/weather_dag.py", line 26, in transform_load_data
    pressure = data["mai"]["pressure"]
               ~~~~^^^^^^^
KeyError: 'mai'
[2024-05-09T10:47:08.332+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-09T10:46:33.057547+00:00, execution_date=20240509T104633, start_date=20240509T104707, end_date=20240509T104708
[2024-05-09T10:47:08.362+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task transform_load_weather_data ('mai'; 91674)
[2024-05-09T10:47:08.388+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T10:47:08.411+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T10:47:08.415+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
