[2024-05-09T10:49:41.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T10:49:41.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T10:49:08.801754+00:00 [queued]>
[2024-05-09T10:49:41.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T10:49:08.801754+00:00 [queued]>
[2024-05-09T10:49:41.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-09T10:49:41.740+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-09 10:49:08.801754+00:00
[2024-05-09T10:49:41.761+0000] {standard_task_runner.py:63} INFO - Started process 93479 to run task
[2024-05-09T10:49:41.775+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-09T10:49:08.801754+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpz5enuc0q']
[2024-05-09T10:49:41.778+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask transform_load_weather_data
[2024-05-09T10:49:41.934+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-09T10:49:08.801754+00:00 [running]> on host ubuntu2204
[2024-05-09T10:49:42.278+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T10:49:08.801754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T10:49:08.801754+00:00'
[2024-05-09T10:49:42.286+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T10:49:42.310+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T10:49:42.313+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow/dags/weather_dag.py", line 28, in transform_load_data
    wind_speed = data["main"]["wind_speed"]
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'wind_speed'
[2024-05-09T10:49:42.329+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-09T10:49:08.801754+00:00, execution_date=20240509T104908, start_date=20240509T104941, end_date=20240509T104942
[2024-05-09T10:49:42.410+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task transform_load_weather_data ('wind_speed'; 93479)
[2024-05-09T10:49:42.476+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T10:49:42.509+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T10:49:42.512+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
