[2024-05-23T11:06:27.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T11:06:27.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [queued]>
[2024-05-23T11:06:27.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [queued]>
[2024-05-23T11:06:27.266+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-05-23T11:06:27.375+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_joined_data> on 2024-05-23 11:02:24.641410+00:00
[2024-05-23T11:06:27.415+0000] {standard_task_runner.py:63} INFO - Started process 85598 to run task
[2024-05-23T11:06:27.482+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'load_joined_data', 'manual__2024-05-23T11:02:24.641410+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmp9vcvtlib']
[2024-05-23T11:06:27.520+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask load_joined_data
[2024-05-23T11:06:27.802+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [running]> on host ubuntu2204
[2024-05-23T11:06:28.046+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='load_joined_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T11:02:24.641410+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T11:02:24.641410+00:00'
[2024-05-23T11:06:28.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T11:06:28.107+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T11:06:28.110+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: save_joined_data_into_S3() missing 1 required positional argument: 'task_instane'
[2024-05-23T11:06:28.134+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_parallel, task_id=load_joined_data, run_id=manual__2024-05-23T11:02:24.641410+00:00, execution_date=20240523T110224, start_date=20240523T110627, end_date=20240523T110628
[2024-05-23T11:06:28.244+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 197 for task load_joined_data (save_joined_data_into_S3() missing 1 required positional argument: 'task_instane'; 85598)
[2024-05-23T11:06:28.339+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T11:06:28.504+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T11:06:28.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
