[2024-05-23T11:04:18.816+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T11:04:18.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [queued]>
[2024-05-23T11:04:18.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [queued]>
[2024-05-23T11:04:18.978+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-23T11:04:19.051+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_joined_data> on 2024-05-23 11:02:24.641410+00:00
[2024-05-23T11:04:19.070+0000] {standard_task_runner.py:63} INFO - Started process 84752 to run task
[2024-05-23T11:04:19.084+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'load_joined_data', 'manual__2024-05-23T11:02:24.641410+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmp8xjr858a']
[2024-05-23T11:04:19.094+0000] {standard_task_runner.py:91} INFO - Job 196: Subtask load_joined_data
[2024-05-23T11:04:19.206+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.load_joined_data manual__2024-05-23T11:02:24.641410+00:00 [running]> on host ubuntu2204
[2024-05-23T11:04:19.500+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='load_joined_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T11:02:24.641410+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T11:02:24.641410+00:00'
[2024-05-23T11:04:19.502+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T11:04:19.526+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T11:04:19.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: save_joined_data_into_S3() missing 1 required positional argument: 'task_instane'
[2024-05-23T11:04:19.566+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_parallel, task_id=load_joined_data, run_id=manual__2024-05-23T11:02:24.641410+00:00, execution_date=20240523T110224, start_date=20240523T110418, end_date=20240523T110419
[2024-05-23T11:04:19.659+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 196 for task load_joined_data (save_joined_data_into_S3() missing 1 required positional argument: 'task_instane'; 84752)
[2024-05-23T11:04:19.729+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T11:04:19.779+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T11:04:19.781+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
