[2024-05-09T08:20:55.236+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T08:20:55.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weater_api_ready manual__2024-05-09T08:20:43.980228+00:00 [queued]>
[2024-05-09T08:20:55.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weater_api_ready manual__2024-05-09T08:20:43.980228+00:00 [queued]>
[2024-05-09T08:20:55.283+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-09T08:20:55.355+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weater_api_ready> on 2024-05-09 08:20:43.980228+00:00
[2024-05-09T08:20:55.371+0000] {standard_task_runner.py:63} INFO - Started process 24734 to run task
[2024-05-09T08:20:55.378+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weater_api_ready', 'manual__2024-05-09T08:20:43.980228+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp4ewa1a0v']
[2024-05-09T08:20:55.381+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask is_weater_api_ready
[2024-05-09T08:20:55.526+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weater_api_ready manual__2024-05-09T08:20:43.980228+00:00 [running]> on host ubuntu2204
[2024-05-09T08:20:55.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weater_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:20:43.980228+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T08:20:43.980228+00:00'
[2024-05-09T08:20:55.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T08:20:55.809+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-09T08:20:55.810+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Kyiv&appid=a2fc2ab52b832be75e0040a88f3e406a
[2024-05-09T08:20:55.834+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-05-09T08:20:56.563+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-09T08:20:56.565+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T08:20:56.578+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weater_api_ready, run_id=manual__2024-05-09T08:20:43.980228+00:00, execution_date=20240509T082043, start_date=20240509T082055, end_date=20240509T082056
[2024-05-09T08:20:56.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T08:20:56.732+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T08:20:56.733+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
