[2024-05-23T10:41:31.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T10:41:31.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_parallel.join_data_in_postgres manual__2024-05-23T10:04:19.618668+00:00 [queued]>
[2024-05-23T10:41:31.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_parallel.join_data_in_postgres manual__2024-05-23T10:04:19.618668+00:00 [queued]>
[2024-05-23T10:41:31.403+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-23T10:41:31.500+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): join_data_in_postgres> on 2024-05-23 10:04:19.618668+00:00
[2024-05-23T10:41:31.515+0000] {standard_task_runner.py:63} INFO - Started process 76142 to run task
[2024-05-23T10:41:31.571+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag_parallel', 'join_data_in_postgres', 'manual__2024-05-23T10:04:19.618668+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_dag.py', '--cfg-path', '/tmp/tmp0msqxr6q']
[2024-05-23T10:41:31.583+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask join_data_in_postgres
[2024-05-23T10:41:31.789+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag_parallel.join_data_in_postgres manual__2024-05-23T10:04:19.618668+00:00 [running]> on host ubuntu2204
[2024-05-23T10:41:32.100+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag_parallel' AIRFLOW_CTX_TASK_ID='join_data_in_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T10:04:19.618668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T10:04:19.618668+00:00'
[2024-05-23T10:41:32.103+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T10:41:32.142+0000] {sql.py:276} INFO - Executing: 
                SELECT 
                    weather.city,                    
                    description,
                    temperature_farenheit,
                    feels_like_farenheit,
                    minimun_temp_farenheit,
                    maximum_temp_farenheit,
                    pressure,
                    humidity,
                    wind_speed,
                    time_of_record,
                    sunrise_local_time,
                    sunset_local_time,
                    state,
                    census_2020,
                    land_area_sq_mile_2020                    
                FROM weather_data AS weather
                INNER JOIN city_look_up AS city ON city.city = weather.city;
            
[2024-05-23T10:41:32.152+0000] {base.py:84} INFO - Using connection ID '***_conn' for task execution.
[2024-05-23T10:41:32.596+0000] {base.py:84} INFO - Using connection ID '***_conn' for task execution.
[2024-05-23T10:41:33.125+0000] {sql.py:486} INFO - Running statement: 
                SELECT 
                    weather.city,                    
                    description,
                    temperature_farenheit,
                    feels_like_farenheit,
                    minimun_temp_farenheit,
                    maximum_temp_farenheit,
                    pressure,
                    humidity,
                    wind_speed,
                    time_of_record,
                    sunrise_local_time,
                    sunset_local_time,
                    state,
                    census_2020,
                    land_area_sq_mile_2020                    
                FROM weather_data AS weather
                INNER JOIN city_look_up AS city ON city.city = weather.city;
            , parameters: None
[2024-05-23T10:41:33.216+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T10:41:33.220+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 434, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/denys/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 491, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "minimun_temp_farenheit" does not exist
LINE 7:                     minimun_temp_farenheit,
                            ^
HINT:  Perhaps you meant to reference the column "weather.minimum_temp_farenheit".

[2024-05-23T10:41:33.258+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_parallel, task_id=join_data_in_***, run_id=manual__2024-05-23T10:04:19.618668+00:00, execution_date=20240523T100419, start_date=20240523T104131, end_date=20240523T104133
[2024-05-23T10:41:33.362+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 174 for task join_data_in_*** (column "minimun_temp_farenheit" does not exist
LINE 7:                     minimun_temp_farenheit,
                            ^
HINT:  Perhaps you meant to reference the column "weather.minimum_temp_farenheit".
; 76142)
[2024-05-23T10:41:33.392+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T10:41:33.430+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T10:41:33.433+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
