[2024-06-10T13:28:27.289+0000] {processor.py:161} INFO - Started process (PID=7039) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:28:27.297+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:28:27.312+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:28:27.311+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:28:27.355+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:28:27.342+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-06-10T13:28:27.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:28:28.360+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 1.138 seconds
[2024-06-10T13:28:59.325+0000] {processor.py:161} INFO - Started process (PID=7282) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:28:59.327+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:28:59.332+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:28:59.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:28:59.348+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:28:59.344+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-06-10T13:28:59.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:28:59.587+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.281 seconds
[2024-06-10T13:29:30.452+0000] {processor.py:161} INFO - Started process (PID=7532) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:29:30.464+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:29:30.472+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:29:30.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:29:30.508+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:29:30.501+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-06-10T13:29:30.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:29:30.622+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.190 seconds
[2024-06-10T13:30:01.118+0000] {processor.py:161} INFO - Started process (PID=7887) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:30:01.143+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:30:01.146+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:30:01.145+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:30:01.267+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:30:01.254+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-06-10T13:30:01.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:30:01.533+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.442 seconds
[2024-06-10T13:30:31.938+0000] {processor.py:161} INFO - Started process (PID=8125) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:30:31.943+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:30:31.952+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:30:31.950+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:30:31.969+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:30:31.966+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-06-10T13:30:31.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:30:32.026+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.110 seconds
[2024-06-10T13:31:02.791+0000] {processor.py:161} INFO - Started process (PID=8220) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:02.796+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:31:02.800+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:31:02.799+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:02.838+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:31:02.831+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 821, in expand
    return cls._expand(expr_format, hash_id=hash_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/croniter/croniter.py", line 659, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 447, in _process_modules
    dag.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dag.py", line 775, in validate
    self.timetable.validate()
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-06-10T13:31:02.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:02.951+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.184 seconds
[2024-06-10T13:31:14.772+0000] {processor.py:161} INFO - Started process (PID=8268) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:14.780+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:31:14.786+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:31:14.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:14.794+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:31:14.792+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:31:14.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:14.894+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.145 seconds
[2024-06-10T13:31:45.693+0000] {processor.py:161} INFO - Started process (PID=8468) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:45.696+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:31:45.703+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:31:45.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:45.714+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:31:45.711+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:31:45.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:31:45.839+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.167 seconds
[2024-06-10T13:32:16.204+0000] {processor.py:161} INFO - Started process (PID=8708) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:32:16.220+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:32:16.225+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:32:16.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:32:16.235+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:32:16.232+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:32:16.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:32:16.331+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.165 seconds
[2024-06-10T13:32:47.078+0000] {processor.py:161} INFO - Started process (PID=8904) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:32:47.081+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:32:47.091+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:32:47.089+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:32:47.103+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:32:47.100+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:32:47.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:32:47.204+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.146 seconds
[2024-06-10T13:33:17.801+0000] {processor.py:161} INFO - Started process (PID=9044) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:17.805+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:33:17.817+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:33:17.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:17.826+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:33:17.823+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:33:17.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:17.999+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.223 seconds
[2024-06-10T13:33:21.964+0000] {processor.py:161} INFO - Started process (PID=9069) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:21.970+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:33:21.976+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:33:21.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:21.987+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:33:21.984+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:33:21.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:22.064+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.121 seconds
[2024-06-10T13:33:52.464+0000] {processor.py:161} INFO - Started process (PID=9192) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:52.470+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:33:52.480+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:33:52.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:52.490+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:33:52.488+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:33:52.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:33:52.579+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.139 seconds
[2024-06-10T13:34:23.654+0000] {processor.py:161} INFO - Started process (PID=9333) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:34:23.666+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:34:23.697+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:34:23.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:34:23.718+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:34:23.716+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:34:23.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:34:23.812+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.190 seconds
[2024-06-10T13:34:43.876+0000] {processor.py:161} INFO - Started process (PID=9486) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:34:43.879+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:34:43.882+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:34:43.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:34:43.886+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:34:43.885+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:34:43.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:34:43.935+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.071 seconds
[2024-06-10T13:35:15.080+0000] {processor.py:161} INFO - Started process (PID=9515) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:35:15.086+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:35:15.093+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:35:15.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:35:15.102+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:35:15.100+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:35:15.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:35:15.183+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.125 seconds
[2024-06-10T13:35:46.287+0000] {processor.py:161} INFO - Started process (PID=9576) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:35:46.295+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:35:46.302+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:35:46.302+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:35:46.310+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:35:46.308+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:35:46.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:35:46.381+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.115 seconds
[2024-06-10T13:36:17.526+0000] {processor.py:161} INFO - Started process (PID=9578) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:36:17.559+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:36:17.569+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:36:17.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:36:17.583+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:36:17.581+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:36:17.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:36:17.771+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.263 seconds
[2024-06-10T13:36:48.628+0000] {processor.py:161} INFO - Started process (PID=9640) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:36:48.637+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:36:48.651+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:36:48.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:36:48.665+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:36:48.661+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:36:48.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:36:48.758+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.155 seconds
[2024-06-10T13:37:18.907+0000] {processor.py:161} INFO - Started process (PID=9642) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:37:18.914+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:37:18.920+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:37:18.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:37:18.931+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:37:18.928+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:37:18.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:37:19.024+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.142 seconds
[2024-06-10T13:37:49.819+0000] {processor.py:161} INFO - Started process (PID=9703) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:37:49.825+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:37:49.832+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:37:49.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:37:49.841+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:37:49.839+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:37:49.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:37:49.924+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.129 seconds
[2024-06-10T13:38:20.248+0000] {processor.py:161} INFO - Started process (PID=9705) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:38:20.252+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:38:20.259+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:38:20.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:38:20.269+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:38:20.267+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:38:20.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:38:20.321+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.099 seconds
[2024-06-10T13:38:50.652+0000] {processor.py:161} INFO - Started process (PID=9826) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:38:50.655+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:38:50.660+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:38:50.660+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:38:50.667+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:38:50.665+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:38:50.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:38:50.728+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.088 seconds
[2024-06-10T13:39:20.999+0000] {processor.py:161} INFO - Started process (PID=9970) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:21.000+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:39:21.003+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:39:21.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:21.010+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:39:21.006+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:39:21.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:21.055+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.069 seconds
[2024-06-10T13:39:25.800+0000] {processor.py:161} INFO - Started process (PID=10054) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:25.804+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:39:25.814+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:39:25.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:25.827+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:39:25.824+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:39:25.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:25.928+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.150 seconds
[2024-06-10T13:39:56.669+0000] {processor.py:161} INFO - Started process (PID=11024) to work on /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:56.672+0000] {processor.py:830} INFO - Processing file /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py for tasks to queue
[2024-06-10T13:39:56.680+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:39:56.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:56.692+0000] {logging_mixin.py:188} INFO - [2024-06-10T13:39:56.689+0000] {dagbag.py:355} ERROR - Failed to import: /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
Traceback (most recent call last):
  File "/home/denys/workspace/de-projects/customer_churn/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py", line 22
    session = AwsGenericHooks.(aes_conn_id='aws_s3_conn')
                              ^
SyntaxError: invalid syntax
[2024-06-10T13:39:56.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py
[2024-06-10T13:39:56.787+0000] {processor.py:183} INFO - Processing /home/denys/workspace/de-projects/customer_churn/airflow/dags/customer_churn_dag.py took 0.138 seconds
